apiVersion: v1
kind: ConfigMap
metadata:
  name: ca-apache-config
  labels:
    app.kubernetes.io/name: ca-apache-config
data:
  overrides.conf: |
    Listen 8080
    ServerName ca.united

    ErrorLog /dev/stderr
    TransferLog /dev/stdout
