apiVersion: apps/v1
kind: Deployment
metadata:
  name: ca
  labels:
    app.kubernetes.io/name: ca
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ca
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ca
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
        - name: apache
          image: httpd:2.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: apache-config
              mountPath: /usr/local/apache2/conf/httpd.conf
              subPath: httpd.conf
              readOnly: true
            - name: apache-run
              mountPath: /usr/local/apache2/logs
            - name: ca
              mountPath: /usr/local/apache2/htdocs/ca.pem
              subPath: ca.pem
              readOnly: true
            - name: trust-bundle
              mountPath: /usr/local/apache2/htdocs/trust-bundle.pem
              subPath: trust-bundle.pem
              readOnly: true
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi
      volumes:
        - name: apache-config
          configMap:
            name: ca-apache-config
        - name: apache-run
          emptyDir: {}
        - name: ca
          configMap:
            name: "ca.pem"
        - name: trust-bundle
          configMap:
            name: 4546b
